device: /dev/ttyACM0
frame_id: ublox_gps
uart1:
  baudrate: 115200
config_on_startup: true
rate: 20                     # in Hz
nav_rate: 1                  # [# of measurement cycles], recommended 1 Hz, may
dgnss_mode: 3                # Fixed mode
dynamic_model: automotive    # automative mode
use_adr: true

inf:
  all: false                   # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  all: false
  esf:
    meas: true
  mon_hw: false
  nav:
    status: true
    pvt: true
    posecef: false
    hpposllh: true
